version: 0.2

env:    
  variables:
    bucket: "$bucket"
    region: "$region"
    key: "$key"
    branch: "$branch"
    app_name: "$app_name"
    availability_zone: "$availability_zone"
    blueprint_id: "$blueprint_id"
    bundle_id: "$bundle_id"
    has_static_ip: "$has_static_ip"

phases:
  build:
    commands:

      - mkdir -p app
      - cd app
      - curl -o terraform_1.5.5_linux_arm64.zip https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_arm64.zip
      - unzip terraform_1.5.5_linux_arm64.zip
      - chmod 755 terraform
      - cd ..
      - printf 'yes' | app/terraform init -backend-config="bucket=$bucket" -backend-config="region=$region" -backend-config="key=$key"
      - app/terraform workspace list      
      - app/terraform workspace select $branch || app/terraform workspace new $branch
      - app/terraform apply --auto-approve -var "app_name=$app_name" -var "region=$region" -var "availability_zone=$availability_zone" -var "blueprint_id=$blueprint_id" -var "bundle_id=$bundle_id" -var "has_static_ip=$has_static_ip" 
